--DROP TABLE CUESTIONARIO;
CREATE TABLE CUESTIONARIO(
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
  NOMBRE VARCHAR(100) NOT NULL,
  NUMERO_REACTIVOS INTEGER,
  FECHA_CREACION DATE,
  TIPO_CUESTIONARIO VARCHAR(10),
  RATING DECIMAL(3,2)
);

INSERT INTO CUESTIONARIO(NOMBRE, NUMERO_REACTIVOS, FECHA_CREACION, TIPO_CUESTIONARIO) 
    VALUES('Quiz 01', 10, '2014-10-01', 'QUIZ');
INSERT INTO CUESTIONARIO(NOMBRE, NUMERO_REACTIVOS, FECHA_CREACION, TIPO_CUESTIONARIO) 
    VALUES('Repaso Lección 13', 30, '2014-10-15', 'REPASO');