DROP TABLE PREGUNTA;
DROP TABLE CUESTIONARIO;
--
CREATE TABLE CUESTIONARIO(
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
  NOMBRE VARCHAR(100) NOT NULL,
  NUMERO_REACTIVOS INTEGER,
  FECHA_CREACION DATE,
  TIPO_CUESTIONARIO VARCHAR(10),
  RATING DECIMAL(3,2)
);

INSERT INTO CUESTIONARIO(NOMBRE, NUMERO_REACTIVOS, FECHA_CREACION, TIPO_CUESTIONARIO) 
    VALUES('Quiz 01', 10, '2014-10-01', 'QUIZ');
INSERT INTO CUESTIONARIO(NOMBRE, NUMERO_REACTIVOS, FECHA_CREACION, TIPO_CUESTIONARIO) 
    VALUES('Repaso Lección 13', 30, '2014-10-15', 'REPASO');

CREATE TABLE PREGUNTA(
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
  ID_CUESTIONARIO INTEGER NOT NULL REFERENCES CUESTIONARIO(ID),
  NUM INTEGER NOT NULL,
  TEXTO VARCHAR(1000) NOT NULL,
  FECHA_CREACION DATE,
  TIPO_PREGUNTA VARCHAR(10));

INSERT INTO PREGUNTA(ID_CUESTIONARIO, NUM, TEXTO, FECHA_CREACION, TIPO_PREGUNTA)
    VALUES(2,1,'¿Que tipo de clase podemos usar para definir un contrato entre clases?','2014-10-15','ABIERTA');
INSERT INTO PREGUNTA(ID_CUESTIONARIO, NUM, TEXTO, FECHA_CREACION, TIPO_PREGUNTA)
    VALUES(2,2,'¿Que tipo de clase podemos usar para definir la base de una jerarquía de clases pero sin corresponder con un objeto específico?','2014-10-15','ABIERTA');

